9.9

diff --git a/.github/workflows/module.extract-pytests.yaml b/.github/workflows/module.extract-pytests.yaml
--- a/.github/workflows/module.extract-pytests.yaml
+++ b/.github/workflows/module.extract-pytests.yaml
@@ -54,7 +54,7 @@ jobs:
     needs: workflow-parameters
     runs-on: ubuntu-latest
     outputs:
-      pytest_modules: ${{ steps.extract.outputs.pytest_modules }}
+      pytest_files: ${{ steps.extract.outputs.pytest_files }}
       test_functions: ${{ steps.extract.outputs.tests }}
     steps:
 
@@ -75,28 +75,32 @@ jobs:
             --output-filename="${{ inputs.output_filename }}" ;
 
           ## Validate Test-Functions JSON before proceeding
-          jq -e . ${{ inputs.output_filename }} 2>&1>/dev/null;
-          status=$?; #echo -e "Status: ${status}";
-          if [[ ${status} -gt 0 ]]; then
-                  echo -e "Configuration: '${{ inputs.output_filename }}' is not valid JSON object!";
-                  exit 1 ;
-            else  ls -al ${{ inputs.output_filename }} ;
-                  cat ${{ inputs.output_filename }} ;
-          fi ;
-
-          TESTS=$( jq -c '.test_functions' ${{ inputs.output_filename }} ) ;
-          echo -e "tests=$TESTS" >> "$GITHUB_OUTPUT" ;
+          if [[ -e ${{ inputs.output_filename }} ]]; then
+                jq -e . ${{ inputs.output_filename }} 2>&1>/dev/null;
+                status=$?; #echo -e "Status: ${status}";
+                if [[ ${status} -gt 0 ]]; then
+                        echo -e "Configuration: '${{ inputs.output_filename }}' is not valid JSON object!";
+                        exit 1 ;
+                  else  ls -al ${{ inputs.output_filename }} ;
+                        cat ${{ inputs.output_filename }} ;
+                        TESTS=$( jq -c '.test_functions' ${{ inputs.output_filename }} ) ;
+                        echo -e "tests=$TESTS" >> "$GITHUB_OUTPUT" ;
+                fi ;
+            else  echo -e "Warning: '${{ inputs.output_filename }}' is missing/not-found!";
+          fi;
 
           ## Validate Test-Modules JSON before proceeding
-          pytest_modules="pytest_modules.json";
-          jq -e . ${pytest_modules} 2>&1>/dev/null;
-          status=$?; #echo -e "Status: ${status}";
-          if [[ ${status} -gt 0 ]]; then
-                  echo -e "Configuration: '${pytest_modules}' is not valid JSON object!";
-                  exit 1 ;
-            else  ls -al ${pytest_modules};
-                  cat ${pytest_modules};
-          fi ;
-
-          PYTEST_MODULES=$( jq -c 'keys' ${pytest_modules} )
-          echo "pytest_modules=$PYTEST_MODULES" >> $GITHUB_OUTPUT
+          pytest_files="pytest_files.json";
+          if [[ -e ${pytest_files} ]]; then
+                  jq -e . ${pytest_files} 2>&1>/dev/null;
+                  status=$?; #echo -e "Status: ${status}";
+                  if [[ ${status} -gt 0 ]]; then
+                          echo -e "Configuration: '${pytest_files}' is not valid JSON object!";
+                          exit 1 ;
+                    else  ls -al ${pytest_files};
+                          cat ${pytest_files};
+                          PYTEST_FILES=$( jq -c 'keys' ${pytest_files} )
+                          echo "pytest_files=$PYTEST_FILES" >> $GITHUB_OUTPUT
+                  fi ;
+            else  echo -e "Warning: ${pytest_files} is missing/not-found!";
+          fi;
