test4.10

diff --git a/.github/workflows/module.aggregate-results.yaml b/.github/workflows/module.aggregate-results.yaml
--- a/.github/workflows/module.aggregate-results.yaml
+++ b/.github/workflows/module.aggregate-results.yaml
@@ -34,19 +34,29 @@ jobs:
         id: validate_parameters
         run: |
 
-          invalid_params=false ;
-          error_header="Workflow: 'module.aggregate-results' cannot proceed without" ;
+          invalid_params=false;
+          error_header="Error: 'pytest.module-dependencies' cannot proceed without a valid";
 
-          [[ -z "${{ github.event.inputs.github_action }}" ]] && {
-            echo -e "${error_header} a valid GitHub Action." ;
-            invalid_params=true ;
-          } ;
-          [[ -z "${{ github.event.inputs.artifacts_location }}" ]] && {
-            echo -e "${error_header} a valid Artifacts Location." ;
-            invalid_params=true ;
-          } ;
+          # Define your inputs with human-readable labels.
+          declare -A inputs=(
+            ["GitHub Action"]="${{ github.event.inputs.github_action }}"
+            ["Artifacts Location"]="${{ github.event.inputs.artifacts_location }}"
+          );
 
-          [[ ${invalid_params} == true ]] && exit 1 ;
+          # Iterate over the inputs.
+          for label in "${!inputs[@]}"; do
+            echo -e "Input: ${inputs[$label]}";
+            if [[ "${inputs[$label]}" == '' ]]; then
+              echo -e "${error_header} ${label}.";
+              invalid_params=true;
+            fi;
+          done;
+
+          # Exit with error if any input is invalid.
+          if [[ ${invalid_params} == true ]]; then
+            echo -e "Invalid Params: ${invalid_params}";
+            exit 1;
+          fi;
 
   aggregate-pytest-results:
     needs: validate-parameters
