10.0.100

diff --git a/.github/workflows/module.running-pytests.yaml b/.github/workflows/module.running-pytests.yaml
--- a/.github/workflows/module.running-pytests.yaml
+++ b/.github/workflows/module.running-pytests.yaml
@@ -99,6 +99,12 @@ jobs:
         test_function: ${{ fromJson( inputs.test_functions ) }}
     steps:
 
+      - name: Install System Packages
+        id: installing_system_packages
+        run: |
+          sudo apt-get update --yes ;
+          sudo apt-get install tree jq --yes ;
+
       - name: Checkout Repository
         uses: actions/checkout@v4
 
@@ -120,19 +126,22 @@ jobs:
           name: requirements-${{ matrix.python-version }}
           path: .
 
+      - name: Listing Entire Project
+        id: listing_project
+        run: |
+
+          tree -FCla --prune -I .git ${{ github.workspace }} ;
+
       - name: Verify requirements.txt Exists
         run: |
 
-          # ls -shal . ;
-          find . ;
+          if [[ ! -f requirements.txt ]]; then
+                  echo "ERROR: requirements.txt was not found!"
+                  exit 1
+            else  echo -e "requirements.txt found!" ;
+                  cat requirements.txt ;
+          fi
 
-          # # if [[ ! -f requirements.txt ]]; then
-          # #   echo -e "ERROR: requirements.txt is missing!" ;
-          # #   exit 1 ;
-          # # fi ;
-          # # echo -e "requirements.txt found!" ;
-          # # cat requirements.txt ;
-          #
           # if [[ -f requirements.txt ]]; then
           #   echo "Uploading requirements.txt"
           #   actions/upload-artifact@v4 --name requirements-${{ matrix.python-version }} \
@@ -142,17 +151,13 @@ jobs:
           #   exit 1 ;
           # fi ;
 
-          if [[ ! -f requirements.txt ]]; then
-            echo "ERROR: requirements.txt was not found!"
-            exit 1
-          fi
-
       - name: Upload requirements.txt
         if: success()
         uses: actions/upload-artifact@v4
         with:
           name: requirements-${{ matrix.python-version }}
           path: requirements.txt
+          overwrite: true
 
       - name: Reinstall Dependencies from Cache
         run: |
diff --git a/.github/workflows/module.validate-parameters.yaml b/.github/workflows/module.validate-parameters.yaml
--- a/.github/workflows/module.validate-parameters.yaml
+++ b/.github/workflows/module.validate-parameters.yaml
@@ -45,25 +45,23 @@ jobs:
 
           ## Ensure the variable is set
           if [[ -z "${validated}" ]]; then
-              echo "🚨 ERROR: validated variable is empty!" ;
-              exit 1 ;
+                  echo "🚨 ERROR: the validated response is empty!" ;
+                  exit 1 ;
+            else  ## Validate JSON and capture errors
+                  echo "${validated}" | jq . > /dev/null 2>&1 ;
+                  if [[ $? -ne 0 ]]; then
+                      echo "🚨 ERROR: JSON is malformed!" ;
+                      echo "Raw JSON received:" ;
+                      echo "${validated}" ;
+                      exit 1 ;
+                  fi ;
           fi ;
 
-          ## Validate JSON and capture errors
-          echo "${validated}" | jq . > /dev/null 2>&1 ;
-          if [[ $? -ne 0 ]]; then
-              echo "🚨 ERROR: JSON is malformed!" ;
-              echo "Raw JSON received:" ;
-              echo "${validated}" ;
-              exit 1 ;
-          fi ;
+          # Ensure JSON is formatted as a single line
+          validated_compact=$(echo "$validated" | jq -c .)
 
-          ## Convert JSON to a single-line format
-          validated_compact=$(echo "${validated}" | jq -c . ) ;
+          # Debugging: Print the formatted JSON before setting it as output
+          echo "Validated JSON Output: ${validated_compact}"
 
-          ## Confirm final JSON format
-          echo "✅ Valid JSON:" ;
-          echo "${validated_compact}" | jq . ;
-
-          ## Write to GitHub output
-          echo "validated=$validated_compact" >> "$GITHUB_OUTPUT" ;
+          # Set the validated parameters to GitHub output
+          echo "validated=$validated_compact" >> "$GITHUB_OUTPUT"
