10.0.97

diff --git a/.github/workflows/module.running-pytests.yaml b/.github/workflows/module.running-pytests.yaml
--- a/.github/workflows/module.running-pytests.yaml
+++ b/.github/workflows/module.running-pytests.yaml
@@ -78,29 +78,16 @@ jobs:
         run: |
           set ;
 
-      - name: Listing GitHub Environment Variables
-        id: github_environment
-        run: |
-          echo "GitHub Environment: ${GITHUB_ENV}" ;
-          cat ${GITHUB_ENV} ;
-
-      - name: Listing GitHub Output Variables
-        id: github_output
-        run: |
-
-          echo "GitHub Environment: ${GITHUB_OUTPUT}" ;
-          cat ${GITHUB_OUTPUT} ;
-
-      - name: Extract Test Files from GITHUB_OUTPUT
-        id: extract
-        run: |
-
-          echo "Extracting test files from GITHUB_OUTPUT..." ;
-          if [[ -z "${{ needs.extract-pytests.outputs.pytest_files }}" ]]; then
-            echo "pytest_files=[]" >> $GITHUB_OUTPUT ;
-          else
-            echo "pytest_files=${{ needs.extract-pytests.outputs.pytest_files }}" >> $GITHUB_OUTPUT
-          fi ;
+      # - name: Extract Test Files from GITHUB_OUTPUT
+      #   id: extract
+      #   run: |
+      #
+      #     echo "Extracting test files from GITHUB_OUTPUT..." ;
+      #     if [[ -z "${{ needs.extract-pytests.outputs.pytest_files }}" ]]; then
+      #       echo "pytest_files=[]" >> $GITHUB_OUTPUT ;
+      #     else
+      #       echo "pytest_files=${{ needs.extract-pytests.outputs.pytest_files }}" >> $GITHUB_OUTPUT
+      #     fi ;
 
   # outter-matrix:
   #   needs: pytest-files
@@ -145,24 +132,39 @@ jobs:
           name: requirements-${{ matrix.python-version }}
           path: .
 
+      - name: Debug: List Files
+        run: ls -R .
+
       - name: Verify requirements.txt Exists
         run: |
 
-          # if [[ ! -f requirements.txt ]]; then
-          #   echo -e "ERROR: requirements.txt is missing!" ;
+          # # if [[ ! -f requirements.txt ]]; then
+          # #   echo -e "ERROR: requirements.txt is missing!" ;
+          # #   exit 1 ;
+          # # fi ;
+          # # echo -e "requirements.txt found!" ;
+          # # cat requirements.txt ;
+          #
+          # if [[ -f requirements.txt ]]; then
+          #   echo "Uploading requirements.txt"
+          #   actions/upload-artifact@v4 --name requirements-${{ matrix.python-version }} \
+          #                              --path requirements.txt ;
+          # else
+          #   echo "ERROR: requirements.txt is missing before upload!" ;
           #   exit 1 ;
           # fi ;
-          # echo -e "requirements.txt found!" ;
-          # cat requirements.txt ;
 
-          if [[ -f requirements.txt ]]; then
-            echo "Uploading requirements.txt"
-            actions/upload-artifact@v4 --name requirements-${{ matrix.python-version }} \
-                                       --path requirements.txt ;
-          else
-            echo "ERROR: requirements.txt is missing before upload!" ;
-            exit 1 ;
-          fi ;
+          if [[ ! -f requirements.txt ]]; then
+            echo "ERROR: requirements.txt was not found!"
+            exit 1
+          fi
+
+      - name: Upload requirements.txt
+        if: success()
+        uses: actions/upload-artifact@v4
+        with:
+          name: requirements-${{ matrix.python-version }}
+          path: requirements.txt
 
       - name: Reinstall Dependencies from Cache
         run: |
@@ -175,6 +177,7 @@ jobs:
 
           # pytests_location="${{ fromJson( needs.workflow.outputs.validated ).pytests_location }}" ;
           pytests_location="tests/requirements/dependencies" ;  ## Warning: Needs to be fixed
+
           pytest -v --junitxml=pytest-results.xml \
           "${pytests_location}/test_dependencies.py::${{ matrix.test_function }}" ;
 
