Updating code-features 01/99

diff --git a/.github/workflows/module.aggregate-results.yaml b/.github/workflows/module.aggregate-results.yaml
--- a/.github/workflows/module.aggregate-results.yaml
+++ b/.github/workflows/module.aggregate-results.yaml
@@ -12,9 +12,10 @@ on:
         required: true
         type: string
 
-      artifacts_path:
+      artifacts_location:
         required: true
         type: string
+        default: "artifacts"
 
     outputs:
 
@@ -24,7 +25,21 @@ on:
 
 jobs:
 
+  github-action:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Check GitHub Action
+        id: github_action
+        run: |
+          if [[ -z "${{ inputs.github_action }}" ]]; then
+            echo -en "Error: inputs.github_action must be provided. " ;
+            echo -e  "The workflow cannot proceed without a valid GitHub Action." ;
+            exit 1 ;
+          fi ;
+
   aggregate-pytest-results:
+    needs: github-action
     runs-on: ubuntu-latest
     outputs:
       aggregated_results: "true"
@@ -54,7 +69,7 @@ jobs:
         id: downloading_artifacts
         uses: actions/download-artifact@v4
         with:
-          path: ${{ inputs.artifacts_path }}/
+          path: ${{ inputs.artifacts_location }}/
 
       - name: Verify Downloaded Artifacts
         id: verifying_artifacts
diff --git a/.github/workflows/module.execute-module.yaml b/.github/workflows/module.execute-module.yaml
--- a/.github/workflows/module.execute-module.yaml
+++ b/.github/workflows/module.execute-module.yaml
@@ -8,13 +8,27 @@ on:
 
     inputs:
 
-      package_path:
+      packages_location:
         required: true
         type: string
 
 jobs:
 
+  packages-location:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Check Package Location
+        id: packages_location
+        run: |
+          if [[ -z "${{ inputs.packages_location }}" ]]; then
+            echo -en "Error: inputs.packages_location must be provided. " ;
+            echo -e  "The workflow cannot proceed without a valid Package Location." ;
+            exit 1 ;
+          fi ;
+
   execute-module:
+    needs: packages-location
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -63,6 +77,6 @@ jobs:
 
       - name: Convert Path & Execute Python Module
         run: |
-          package_module=$( echo "${{ inputs.package_path }}" | sed 's/\//./g' ) ;
+          package_module=$( echo "${{ inputs.packages_location }}" | sed 's/\//./g' ) ;
           echo "Executing Python module: ${package_module}" ;
           python -m $package_module ;
diff --git a/.github/workflows/module.extract-pytests.yaml b/.github/workflows/module.extract-pytests.yaml
--- a/.github/workflows/module.extract-pytests.yaml
+++ b/.github/workflows/module.extract-pytests.yaml
@@ -8,6 +8,10 @@ on:
 
     inputs:
 
+      pytests_location:
+        required: true
+        type: string
+
       github_action:
         required: true
         type: string
@@ -20,7 +24,34 @@ on:
 
 jobs:
 
+  pytests-location:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Check PyTests Location
+        id: pytests_location
+        run: |
+          if [[ -z "${{ inputs.pytests_location }}" ]]; then
+            echo -en "Error: inputs.pytests_location must be provided. " ;
+            echo -e  "The workflow cannot proceed without a valid PyTests Location." ;
+            exit 1 ;
+          fi ;
+
+  github-action:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Check GitHub Action
+        id: github_action
+        run: |
+          if [[ -z "${{ inputs.github_action }}" ]]; then
+            echo -en "Error: inputs.github_action must be provided. " ;
+            echo -e  "The workflow cannot proceed without a valid GitHub Action." ;
+            exit 1 ;
+          fi ;
+
   extract-pytests:
+    needs: [pytests-location, github-action]
     runs-on: ubuntu-latest
     outputs:
       test_functions: ${{ steps.extract.outputs.tests }}
diff --git a/.github/workflows/module.install-packages.yaml b/.github/workflows/module.install-packages.yaml
--- a/.github/workflows/module.install-packages.yaml
+++ b/.github/workflows/module.install-packages.yaml
@@ -8,13 +8,27 @@ on:
 
     inputs:
 
-      package_path:
+      packages_location:
         required: true
         type: string
 
 jobs:
 
+  packages-location:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Check Packages Location
+        id: packages_location
+        run: |
+          if [[ -z "${{ inputs.packages_location }}" ]]; then
+            echo -en "Error: inputs.packages_location must be provided. " ;
+            echo -e  "The workflow cannot proceed without a valid Package Location." ;
+            exit 1 ;
+          fi ;
+
   install-packages:
+    needs: packages-location
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -36,7 +50,7 @@ jobs:
 
       - name: Generate requirements.txt from JSON
         run: |
-          PACKAGE_PARENT_DIR="$( dirname ${{ inputs.package_path }} )";
+          PACKAGE_PARENT_DIR="$( dirname ${{ inputs.packages_location }} )";
           jq -r '
             .dependencies[] |
             if .version.target then
diff --git a/.github/workflows/module.running-pytests.yaml b/.github/workflows/module.running-pytests.yaml
--- a/.github/workflows/module.running-pytests.yaml
+++ b/.github/workflows/module.running-pytests.yaml
@@ -14,7 +14,30 @@ on:
 
 jobs:
 
+  test-functions:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Check PyTest Functions
+        id: test_functions
+        run: |
+          if [[ -z "${{ inputs.test_functions }}" ]]; then
+            echo -en "Error: inputs.test_functions must be provided. " ;
+            echo -e  "The workflow cannot proceed without a valid Test Functions." ;
+            exit 1 ;
+          fi ;
+
+      # - name: Check PyTest Functions
+      #   id: test_functions
+      #   run: |
+      #     echo "Received Test Functions Input: '${{ inputs.test_functions }}'" ;
+      #     if [[ -z "${{ inputs.test_functions }}" || "${{ inputs.test_functions }}" == "[]" ]]; then
+      #       echo -e "ERROR: inputs.test_functions is empty!" ;
+      #       exit 1 ;
+      #     fi ;
+
   running-pytests:
+    needs: test-functions
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -65,7 +88,7 @@ jobs:
       - name: Run Pytest Function
         run: |
           pytest -v --junitxml=pytest-results.xml \
-          "${{ inputs.pytests_dir }}/test_dependencies.py::${{ matrix.test_function }}" ;
+          "${{ inputs.pytests_location }}/test_dependencies.py::${{ matrix.test_function }}" ;
 
       - name: Upload Test Results
         uses: actions/upload-artifact@v4
