9.6

diff --git a/.github/workflows/module.extract-pytests.yaml b/.github/workflows/module.extract-pytests.yaml
--- a/.github/workflows/module.extract-pytests.yaml
+++ b/.github/workflows/module.extract-pytests.yaml
@@ -73,11 +73,34 @@ jobs:
             --scripts-location="${{ inputs.github_action }}" \
             --output-filename="${{ inputs.output_filename }}" ;
 
-          if ! jq -e . ${{ inputs.output_filename }} > /dev/null 2>&1; then
-                  echo -e "ERROR: ${{ inputs.output_filename }} is not valid JSON!" ;
+          # if ! jq -e . ${{ inputs.output_filename }} > /dev/null 2>&1; then
+          #         echo -e "ERROR: ${{ inputs.output_filename }} is not valid JSON!" ;
+          #         exit 1 ;
+          #   # else  cat ${{ inputs.output_filename }} ;
+          # fi ;
+
+          ## Validate Test-Functions JSON before proceeding
+          jq -e . ${{ inputs.output_filename }} 2>&1>/dev/null;
+          status=$?; #echo -e "Status: ${status}";
+          if [[ ${status} -gt 0 ]]; then
+                  echo -e "Configuration: '${{ inputs.output_filename }}' is not valid JSON object!";
                   exit 1 ;
-            # else  cat ${{ inputs.output_filename }} ;
+            else  cat ${{ inputs.output_filename }} ;
           fi ;
 
           TESTS=$( jq -c '.test_functions' ${{ inputs.output_filename }} ) ;
           echo -e "tests=$TESTS" >> "$GITHUB_OUTPUT" ;
+
+          ## Validate Test-Modules JSON before proceeding
+          pytest_modules="pytest_modules.json";
+          jq -e . ${pytest_modules} 2>&1>/dev/null;
+          status=$?; #echo -e "Status: ${status}";
+          if [[ ${status} -gt 0 ]]; then
+                  echo -e "Configuration: '${pytest_modules}' is not valid JSON object!";
+                  exit 1 ;
+            else  ls -al ${pytest_modules};
+                  cat ${pytest_modules};
+          fi ;
+
+          TEST_FILES=$( jq -c 'keys' ${pytest_modules} )
+          echo "test_files=$TEST_FILES" >> $GITHUB_OUTPUT
