Finalizing the PyTest workflow

diff --git a/.github/workflows/pytest.module-matrix.yaml b/.github/workflows/pytest.module-matrix.yaml
--- a/.github/workflows/pytest.module-matrix.yaml
+++ b/.github/workflows/pytest.module-matrix.yaml
@@ -89,7 +89,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ${{ fromJson(vars.PYTHON_VERSIONS).python }}  # Ensure the matrix is defined
+        python-version: ${{ fromJson(vars.PYTHON_VERSIONS).python }}
     steps:
 
       - name: Checkout Repository
@@ -105,17 +105,17 @@ jobs:
       - name: Download requirements.txt
         uses: actions/download-artifact@v4
         with:
-          name: requirements-${{ matrix.python-version }}  # Ensure correct name is used
+          name: requirements-${{ matrix.python-version }}
           path: .
 
       - name: Verify requirements.txt Exists
         run: |
           if [[ ! -f requirements.txt ]]; then
-            echo "ERROR: requirements.txt is missing!"
-            exit 1
-          fi
-          echo "requirements.txt found!"
-          cat requirements.txt
+            echo "ERROR: requirements.txt is missing!" ;
+            exit 1 ;
+          fi ;
+          echo "requirements.txt found!" ;
+          cat requirements.txt ;
 
       - name: Install Python and Dependencies
         uses: actions/setup-python@v4
@@ -124,22 +124,16 @@ jobs:
 
       - name: Reinstall Dependencies from Cache
         run: |
-          python -m pip install --upgrade pip
-          python -m pip install -r requirements.txt
-
-      # - name: Execute Python Module
-      #   run: |
-      #     echo -e "Executing Python module..."
-      #     # python -m "${{ inputs.packages_dir }}/dependencies"
-      #     # python -m packages.requirements.dependencies ;
+          python -m pip install --upgrade pip ;
+          python -m pip install -r requirements.txt ;
 
       - name: Set PYTHONPATH to Repository Root
         run: |
-          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
-          echo "PYTHONPATH set to: $GITHUB_WORKSPACE"
+          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV ;
+          echo -e "PYTHONPATH set to: ${GITHUB_WORKSPACE}" ;
 
       - name: Convert Path & Execute Python Module
         run: |
-          MODULE_PATH=$(echo "${{ inputs.packages_dir }}/dependencies" | sed 's/\//./g')
-          echo "Executing Python module: $MODULE_PATH"
-          python -m "$MODULE_PATH"
+          package_module=$( echo "${{ inputs.packages_dir }}" | sed 's/\//./g' ) ;
+          echo "Executing Python module: ${package_module}" ;
+          python -m $package_module ;
